### ISSUE TITLE
Liabilities - Mortgage account_number is sometimes null

### ISSUE THREAD

**Issue by kevindice** [plaid/plaid-openapi#186] opened 2024-12-25 04:35 UTC
The schema says that the `account_number` on a mortgage liability is always a string, but the documentation shows that it can be nullable.  When using the Sandbox environment, the Python client throws an error because the response comes back with a null account_number.

**Comment by phoenixy1** [comment] 2024-12-26 23:53
Thank you for the report! Closing this as a duplicate of https://github.com/plaid/plaid-python/issues/538. Issue will be resolved in the next client library release.

**Closed by phoenixy1** 2024-12-26 23:53 UTC
