### ISSUE TITLE
Should the members of `RemovedTransaction` be required?

### ISSUE THREAD

**Issue by richardasymmetric** [plaid/plaid-openapi#163] opened 2024-04-25 18:01 UTC
Hi, I'm not sure if this is a question, or a bug report, but I'm implementing the transaction sync process (in node/ts) and was wondering if the fields in `RemovedTransaction` should be marked as required. 
Current definition:
```javascript
export interface RemovedTransaction {
    /**
     * The ID of the removed transaction.
     * @type {string}
     * @memberof RemovedTransaction
     */
    transaction_id?: string;
    /**
     * The ID of the account of the removed transaction.
     * @type {string}
     * @memberof RemovedTransaction
     */
    account_id?: string;
}
```

As it stands, the types given by the typescript definition would allow an empty object to be returned, or an object with just an account id. 

Currently valid:
```javascript

removed: RemovedTransaction = {}; // valid
removed: RemovedTransaction = { account_id: "id" }; // valid
removed: RemovedTransaction = { transaction_id: "id" }; //valid
```
In the 3 above situations, I'm not sure how I would interpret what Plaid is trying to tell me.

**Comment by phoenixy1** [comment] 2024-04-25 18:22
Thanks for reporting! This is a duplicate of / the same issue as 

https://github.com/plaid/plaid-node/issues/620

And the answer is that yes, these fields should be required. This has been fixed upstream but the fix hasn't been published yet, it will go out in the next library release.

**Closed by phoenixy1** 2024-04-25 18:22 UTC
